export const ROUTES = {
  HOME: "/",
  MEDICINES: "/medicines",
  MEDICINE_DETAILS: (id: string) => `/medicines/${id}`,
  DOCTORS: "/doctors",
  DOCTOR_DETAILS: (id: string) => `/doctors/${id}`,
  CONDITIONS: "/conditions",
  CONDITION_DETAILS: (id: string) => `/conditions/${id}`,
  BLOGS: "/blogs",
  BLOG_DETAILS: (slug: string) => `/blogs/${slug}`,
  SYMPTOM_CHECKER: "/symptom-checker",
  ABOUT: "/about",
  CONTACT: "/contact",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  AI_ASSISTANT: "/ai-assistant",
  REPORT_ANALYSIS: "/report-analysis",
  HEALTH_RECORDS: "/health-records",
  PATIENTS: "/patients",
  SCHEDULE: "/schedule",
  USERS: "/users",
  REVIEWS: "/reviews",
  ANALYTICS: "/analytics",
  ADMIN_SETTINGS: "/admin/settings",
  MEDICINES_ADD: "/medicines/add",
  MEDICINES_MANAGE: "/medicines/manage",
  BLOGS_CREATE: "/blogs/create",
  BLOGS_MANAGE: "/blogs/manage",
  DOCTORS_MANAGE: "/doctors/manage",
  CONDITIONS_MANAGE: "/conditions/manage",
  DOCTOR_MESSAGES: "/messages",
  REPORT_HISTORY: "/report-analysis/history",
  REVIEWS_MANAGE: "/reviews/manage",
  RECOMMENDATIONS: "/recommendations",
} as const;

export const PUBLIC_ROUTES = [
  ROUTES.HOME,
  ROUTES.MEDICINES,
  ROUTES.DOCTORS,
  ROUTES.CONDITIONS,
  ROUTES.BLOGS,
  ROUTES.SYMPTOM_CHECKER,
  ROUTES.ABOUT,
  ROUTES.CONTACT,
  ROUTES.LOGIN,
  ROUTES.REGISTER,
] as const;

export const PROTECTED_ROUTES = {
  ALL: ["user", "doctor", "admin"],
  USER_ONLY: ["user"],
  DOCTOR_ONLY: ["doctor"],
  ADMIN_ONLY: ["admin"],
  DOCTOR_ADMIN: ["doctor", "admin"],
  ROLE_MAP: {
    [ROUTES.DASHBOARD]: ["user", "doctor", "admin"],
    [ROUTES.PROFILE]: ["user", "doctor", "admin"],
    [ROUTES.HEALTH_RECORDS]: ["user"],
    [ROUTES.AI_ASSISTANT]: ["user", "doctor", "admin"],
    [ROUTES.REPORT_ANALYSIS]: ["user", "doctor", "admin"],
    [ROUTES.PATIENTS]: ["doctor"],
    [ROUTES.SCHEDULE]: ["doctor"],
    [ROUTES.USERS]: ["admin"],
    [ROUTES.REVIEWS]: ["admin"],
    [ROUTES.ANALYTICS]: ["admin"],
    [ROUTES.ADMIN_SETTINGS]: ["admin"],
    [ROUTES.MEDICINES_ADD]: ["doctor"],
    [ROUTES.MEDICINES_MANAGE]: ["doctor", "admin"],
    [ROUTES.BLOGS_CREATE]: ["doctor"],
    [ROUTES.BLOGS_MANAGE]: ["admin"],
    [ROUTES.DOCTORS_MANAGE]: ["admin"],
    [ROUTES.CONDITIONS_MANAGE]: ["admin"],
    [ROUTES.RECOMMENDATIONS]: ["user"],
  } as Record<string, string[]>,
} as const;

export const API_ENDPOINTS = {
  API_INFO: "/",
  HEALTH: "/health",
  AUTH: "/auth",
  MEDICINES: "/medicines",
  MEDICINES_FEATURED: "/medicines/featured",
  DOCTORS: "/doctors",
  DOCTORS_PATIENTS: "/doctors/patients",
  DOCTORS_SCHEDULE: "/doctors/schedule",
  CONDITIONS: "/conditions",
  BLOGS: "/blogs",
  REVIEWS: "/reviews",
  CHAT_SESSIONS: "/chat-sessions",
  REPORT_ANALYSES: "/report-analyses",
  HEALTH_RECORDS: "/records",
  SYMPTOM_ANALYSES: "/symptom-analyses",
  AI: "/ai",
  UPLOAD: "/upload/image",
  STATS: "/stats",
  STATS_DASHBOARD: "/stats/dashboard",
  STATS_ANALYTICS: "/stats/analytics",
  RECORDS: "/records",
} as const;

export const SITE_SECTIONS = [
  { href: ROUTES.HOME, label: "Home" },
  { href: ROUTES.MEDICINES, label: "Medicines" },
  { href: ROUTES.DOCTORS, label: "Doctors" },
  { href: ROUTES.CONDITIONS, label: "Conditions" },
  { href: ROUTES.BLOGS, label: "Health Articles" },
  { href: ROUTES.ABOUT, label: "About" },
] as const;
