export const COMMON_SYMPTOMS = [
  "Fever",
  "Headache",
  "Cough",
  "Sore Throat",
  "Fatigue",
  "Body Ache",
  "Chest Pain",
  "Shortness of Breath",
  "Nausea",
  "Vomiting",
  "Diarrhea",
  "Abdominal Pain",
  "Dizziness",
  "Loss of Appetite",
  "Joint Pain",
  "Muscle Weakness",
  "Skin Rash",
  "Swollen Lymph Nodes",
  "Night Sweats",
  "Weight Loss",
  "Blurred Vision",
  "Frequent Urination",
  "Back Pain",
  "Numbness",
  "Anxiety",
  "Depression",
  "Insomnia",
  "Palpitations",
  "Indigestion",
  "Constipation",
] as const;

export const SEVERITY_LEVELS = [
  { value: "low", label: "Low", color: "bg-green-500", description: "Mild symptoms, no immediate concern" },
  { value: "medium", label: "Medium", color: "bg-yellow-500", description: "Moderate symptoms, should consult a doctor" },
  { value: "high", label: "High", color: "bg-red-500", description: "Severe symptoms, seek medical attention" },
] as const;

export const BODY_PARTS = [
  "Head",
  "Eyes",
  "Ears",
  "Nose",
  "Throat",
  "Neck",
  "Chest",
  "Upper Back",
  "Lower Back",
  "Abdomen",
  "Arms",
  "Legs",
  "Hands",
  "Feet",
  "Skin",
  "General",
] as const;

export const SYMPTOM_DURATIONS = [
  { label: "Less than 24 hours", value: "24h" },
  { label: "1-3 days", value: "1-3d" },
  { label: "3-7 days", value: "3-7d" },
  { label: "1-2 weeks", value: "1-2w" },
  { label: "2-4 weeks", value: "2-4w" },
  { label: "More than a month", value: "1m+" },
] as const;
